import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import 'swiper/css';
import"@fortawesome/fontawesome-free/css/all.min.css"
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "sonner";
import Providers from "@/Providers/Providers";
import Footer from "./_components/Footer/Footer";

export const poppins =  Poppins({
  weight:["100","200","300","400","500","600","700","800"],
  subsets:["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
  className={`${poppins.className} antialiased flex flex-col min-h-screen`}
  suppressHydrationWarning={true}
>
  <Providers>
    <Navbar />
    <Toaster />
    <main className="flex-1">{children}</main>
    <Footer />
  </Providers>
</body>

    </html>
  );
}
